[package]
name = "pbs-fuse-loop"
version = "0.1.0"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"
description = "fuse and loop device helpers"

[dependencies]
anyhow = "1.0"
futures = "0.3"
lazy_static = "1.4"
libc = "0.2"
nix = "0.19.1"
regex = "1.2"
tokio = { version = "1.6", features = [] }

proxmox = "0.12.1"
proxmox-fuse = "0.1.1"

pbs-tools = { path = "../pbs-tools" }
