[package]
name = "pxar-bin"
version = "0.1.0"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"

[[bin]]
name = "pxar"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
futures = "0.3"
nix = "0.19.1"
serde_json = "1.0"
tokio = { version = "1.6", features = [ "rt", "rt-multi-thread" ] }

pathpatterns = "0.1.2"
proxmox = { version = "0.12.1", default-features = false, features = [] }
pxar = { version = "0.10.1", features = [ "tokio-io" ] }

pbs-client = { path = "../pbs-client" }
pbs-runtime = { path = "../pbs-runtime" }
pbs-tools = { path = "../pbs-tools" }
